title: Lynx :)
description: Physics @ UCSB
url: "https://lynxxu.link"
version: 0.0.4
plugins:
  - jekyll-feed
email: lynxxu@ucsb.edu
markdown: kramdown
kramdown:
  input: GFM
collections:
  notes:
    output: true
    permalink: /notes/:name/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: "_posts/2026-03-04-test-post-for -launch-the-website.md"
      type: posts
    values:
      section: notes
exclude:
  - index.markdown
  - README.md
  - Gemfile
  - Gemfile.lock
  - "laptop issue memo.docx"
  - ".idea"
github_username: LynsIsMe
